---
title: "Police Complaints"
author: "Heather Li"
date: "6/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(primer.data)
library(lubridate)
library(janitor)
library(skimr)
library(nycflights13)
library(gapminder)
library(fivethirtyeight)
library(ggthemes)

# It is somewhat sloppy to include a read_csv() command in the setup chunk.
# Normally, we would just load libraries here. However, we have not learned
# about the col_types argument to read_csv() yet, so we can't make the annoying
# message go away unless we stick the call in a code chunk with a code chunk
# option like message = FALSE or include = FALSE.

raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>% 
  select(officer_id) 

nyc <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/nyc_clean.csv") %>% 
  select(OfficerID)

chicago <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/chicago_clean.csv") %>% 
  select(UID)

```


```{r, clean_data, echo = FALSE}

# This code makes a table that lets us know how many times each officer id appeared 
# in the tibble, i.e. how many complaints each officer has.

clean_data <- raw_data %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  
# We now want to know in which percentile (out of 10) each officer is, based on
# the amount of complaints he has. We could use mutate and percentile, as we did 
# multiple times in Wrangling B. But ntile() accomplishes the same in less code.
  
  mutate(compl_dec = ntile(total, 10)) %>% 
  
# As you build a pipe, you want to look at the result after each step to make
# sure it does what you want. Only after it is working would you then assign
# the result to an object which you can use later. 
  
# We want to know the total number of complaints in each decile of officers.
  
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  
# The graph needs total complaints as a percentage, which is easy to
# calculate. Then, we only keep around the variables we need for the plot.
  
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "Philadelphia")
```

```{r, nyc, echo = FALSE}
clean_nyc <- nyc %>% 
  group_by(OfficerID) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "New York City")
```

```{r,chicago, echo = FALSE}
clean_chicago <- chicago %>% 
  group_by(UID) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "Chicago")
```

```{r, joining, echo = FALSE}
final_data <- bind_rows(clean_chicago, clean_nyc, clean_data)
```

```{r, plot_data}
# We could just have one giant pipe which goes directly into ggplot(), like we
# do in the tutorials. There is nothing wrong with that approach, but it is
# often easier to split your work up into separate parts, the better to make
# sure that each part is doing what you want.

final_data %>% 
  ggplot(aes(x = compl_dec, y = compl_perc)) +
    geom_col(fill = if_else(final_data$compl_dec == 10, "#7FD4E6", "#00558F")) +
    labs(title = "In several US cities, a small group of officers generate a\ndisproportionate share of misconduct complaints",
         subtitle = "Distribution of civilian misconduct complaints, by decile",
         x = "Officers are ranked by number of complaints and grouped into deciles",
         y = NULL,
         caption = "Data for Chicago and New York are from 2007 to 2017 and include only closed complaints\nData for Philadelphia are from April 2015 to March 2021 and include pending complaints\nSources: Invisible Institute (Chicago); New York Civil Liberties Union (New York); OpenDataPhilly and\nSam Learner (Philadelphia)") +
    scale_x_continuous(breaks = 1:10) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    facet_wrap(~city,nrow = 1)+
    theme_economist()+
    theme(legend.position = "none")+
    theme(plot.background = element_rect(fill = "#FFF0E3"))
```

